name: 'sind cleanup'
description: 'Delete all sind clusters'

runs:
  using: 'composite'
  steps:
    - name: Delete clusters
      if: always()
      shell: bash
      run: sind $SIND_VERBOSITY delete cluster --all 2>&1 || true
